### PR TITLE
Add Unions support

### PR DESCRIPTION
**Pull request by Xerios**
Love your work on this, thought I would contribute back with my changes

### CODE REVIEW

**Comment by nathsou** [comment]
Hey, @Xerios thanks a lot for your PR, the support is much appreciated.
Union types  are interesting but they are quite tricky!

For instance, there is a small issue with the current implementation:

```rust
mut a: Num | Str = 3 
a = "" // Cannot unify 'Num' with 'Str'
```

Here, `Str` should be assignable to `a`'s type, so if a type is unified with a union type, it should "loose" information and be coerced to the union type.
This implies that this should fail:

```rust
let a: Num | Str = 3
let b: Num = a
```

To allow this, we would need to perform a runtime check to know the actual type of `a` (here `Num`),  
this means that the language is required to support quite an advanced type system with type narrowing (like TypeScript):

```ts
const a: number | string = 3;

if (typeof a === "number") {
    // in this scope, "a" is of type "number"
    const b = a;
}
```

So instead, what would be much simpler to support is tagged unions (aka sum types / algebraic data types) which are unions but with a defined constructor/tag to simplify the narrowing process at runtime using pattern matching.
For instance in Rescript, tagged unions are defined like this:

```rescript
type Option<t> = None | Some<t>
```

Which is very similar to the syntax you introduced for general unions but is restricted to constructor definitions on the right hand side.

TypeScript has evolved as a type system on top of JavaScript so it has to support common patterns which sometimes require a complex type system (like narrowing). Simplicity is a design goal for poy so I think tagged unions (called enums in poy) are preferable in this case. 

This is good timing as I am currently working on enum support, enums in poy have syntax similar to Rust/Swift and are narrowed down using match expressions (pattern matching):

```Rust
enum Option<t> {
    None,
    Some(t),
}

extend<a> Option<a> {
    fun map<b>(f: a -> b) {
        match self {
            None => None
            Some(val) => Some(f(val))
        }
    }
}
```

**Comment by Xerios** [comment]
Fair point, I kind of expected such response. This union implementation came out of the need for creating functions which accept multiple types as parameters. Coercing the type on assignment actually fit perfectly well for my use-case.

My version varies quite a lot from the original, I used Poy as a blueprint for my DSL and been building upon it daily for the past month because your coding style and the mental model fits me well. The overall structure remains the same, but its purpose it's fairly different, far less complex in terms of flexibility. It was a pleasant surprise to see a new commit out of nowhere :)

At first I wanted to get rid of the type system and re-implement my own, because my overall type system knowledge is mediocre. Yet seeing how **powerful** your type system was, I pushed through and managed to extend it with some features from my old language (unions, optional params / default values, named arguments, operator overloading) to the best of my abilities. Mostly I spent time writing debugging, testing and visualization tools around it to help me understand things. All of which I'd like to contribute back eventually.

> (Intermission: fancy unrelated pic before my wall of text)

Code_Pr82AVBLS4

Unfortunately for the past few days I've been struggling with retrofitting the type system, making me once again doubt if I should not simply make my own.

Knowing that you have a far better knowledge of compilers, I hope you don't mind if I dump some of my questions regarding the type system here:

* I still have a poor understanding of overall unification logic:
  * `infer*` always create a new type through `Type.instantiate`, which if I understood correctly creates a new type on the same module/function level, then it is fused using `unify`.
  * `resolveType` links it to the closest type in the scope/context.
  * `TRS`,`normalize` and overall rewrite logic is a big mystery, somehow I have a feeling that this may solve some of my problems mentioned below, but I have failed to wrap my head around it so I top thinking about it.
  * `unifyVar` flow is very confusing still, its been a week diving into your type system and I still don't know understand its journey and behavior.
  * There is seemingly no way to access original expression, such as getting function expression from a function call. This is mostly by design but I haven't figured out a way to access the original function declaration where the type was declared.

* In my version, every type mostly has a form, think of it like the [memory type from Vult](https://vult-dsp.github.io/vult/tutorials/functions/). You could have `[noform:0, constant:1, varied:2, memory:3]` where variables upgraded to but never downgraded (e.g. `constant<int> + varied<int> == varied<int>` ). It's similar to type coercion except that the form propagates back (and pretty much redefines the type). For instance when using `func test(b){b[1]}` should transform the `b` argument into `Memory` of unknown type, then through usage `test(someMemoryNumValue)`, it will infer the remaining type.
  * I tried using generics and extends with different variations, adding operator overloading, but in the end implementing such an integral feature seemed better fit inside the compiler rather as a script.
  * Either I misunderstood some concepts or is it not possible to create *constrained types*. I wanted to make types that are compatible with each other but they would end up loosing their original type in the process. This made me think this is due to lack of implicit casting, because there in my version various kinds of number types exist.
  * `Unify` seems to merge both ways, my initial forms implementation worked inside of it, which seemingly worked until I started encountering cases where the order was switched breaking my simple A > B upgrade logic. I assume `Unify`'s purpose is to closer to an equality check than anything else?

* My current approach is as follows:
  * `Form<_,Constant|Varied|Memory>` as `Fun` variant type, being a top-most wrapper of other types
  * I'm storing the original function expression inside 
  * I left `unify` act as an equality check, but with an additional Form validation and upgrade right before.
  * Using VariableAccess I can transform an uninitialized index access like `a[2]` and upgrade it to a `Form<_,Memory>` form. My upgrade logic isn't but seems to be the right path.
  * My `Form` type seemed to work until I started encountering issues due to `Unbound` vars where I would end up with double wrapped `Form<Form<_,New>,Old>` this made me think perhaps my type should be on the same level as `Fun` and `Var`.
  * I decided to store reference to the function expressions and signatures inside `VarInfo` which allows me to modify its' type
  * ...yet, modifying the function's type seems much harder than I initially thought. I'm thinking about perhaps storing every related type and doing a brute-force approach, but then again I feel like there has to be a simpler way.


> Here's a snippet of my approach to detect `b[1]` and upgrade `b` to `Memory`, I'm still currently trying to get the arguments to update but I feel like either I messed up the link / unify somewhere else due to my lack of knowledge, or perhaps I'm simply how these functions need to be used. 
> All I want to know here is if you don't see anything clearly wrong
```ts
  VariableAccess: ({ lhs, field, typeParams, isCalled }) => {
    // ...
    if (notAnArray && (!hasForm || isUnboundVar)) {
      // upgrade logic
      if (Type.utils.isFormLessThan(lhsTy, Forms.Memory)) {
        //------- this.upgradeForm(lhsTy, lhs as HasType<Expr>, Forms.Memory)
        //        ^^^^^^^^^^^^^^^^
        //        This func does something like this:
        this.variables.lookup(name).do((varInfo)=> {
          if (!Type.utils.isForm(varInfo.ty)) { 
            // wrap form logic, in this case there's already a Form
          }else{
            // modify its arg[1] to Form.Memory type
            Type.changeForm(varInfo.ty, form) 
            // create new wrapped type Form<{lhsTy}, Forms.Memory>
            const newTy = Type.withForm(Type.instantiate(varInfo.ty, this.letLevel, this.generics).ty, form)
            // unify black magic 
            this.unify(varInfo.ty, newTy) 
            this.unify(ty, newTy)
            // varInfo.value is defined on type declaration, seems like this part 
            // is unecessary because one of previous unified the changes somehow
            this.unify(varInfo.value.ty, newTy)
          }
        })
        //-------
      }

      // extract the inner type e.g. Form<Int, Varied> -> Int
      const lhsTyUnwrap = Type.utils.unwrapForm(lhsTy) 
      // create new type instance of Int
      const innerTy = Type.instantiate(lhsTyUnwrap, this.letLevel, this.generics).ty
      // index access is always a Form<Int, Varied>
      const argTy = Type.withForm(Type.Int, Forms.Varied)
      // return type is always Form<{innerTy}, Varied>
      const reTy = Type.withForm(Type.instantiate(innerTy, this.letLevel, this.generics).ty, Forms.Varied)
      // defines the a[1] function signature (int)=>{reTy}
      return Type.Function([argTy], reTy)
    }
  //...
```

While writing this I've been rubberducking myself and I'm still getting new ideas and insight on my mistakes.

> I've added some eyecandy pics of my debugging tools to make my post less painful to read :)

Code_gJwVudLnd7

**Comment by nathsou** [comment]
Nice visualizations!

> This union implementation came out of the need for creating functions which accept multiple types as parameters. Coercing the type on assignment actually fit perfectly well for my use-case.

I see, in this case I think the type system you envision is incompatible with poy's, since you described features which require subtyping. Poy's type systems implements a standard Hindley-Milner type system which assigns each member the "most general" type it can have and [does not support subtyping by default](https://www.wikiwand.com/en/Hindley%E2%80%93Milner_type_system#Subtyping), i.e. `Num` is a subtype of `Num | Str`. Instead, the unification process should be commutative, `unify(Num, Num | Str)` should be the same as `unify(Num | Str, Num)`, as you said it equates types.

I decided to use a Hindley-Milner type system as it can infer the type of most expressions without the need for manual type annotations but it might not be the best fit for your needs, it's a bit complex and not super efficient. So if you want to use poy as a basis for your own DSL, maybe you could reuse just the pieces that fit your project, like the lexer/parser and use your own simpler type system with support for forms and subtyping.

**Questions**:
Sorry, I should have put more comments in the code.

> 1. infer* always create a new type through Type.instantiate, which if I understood correctly creates a new type on the same module/function level, then it is fused using unify.

In most cases, `Type.instantiate` is not required, it is only used when the type is generalized, i.e. made polymorphic, for instance:

```rust
let id = x -> x
```

is first inferred to be of type `a -> a`, but if we then infer `(id(3), id(""))` we would get a type error since when evaluating `id(3)`, the type variable `a` is unified with `Num`. So we need to determine which type variables are free and make them polymorphic/generalize them. So we would get `id: forall a. a -> a` and each time we resolve `id`, we instantiate its type, so we would for instance get `b -> b` for `id(3)` and then `c -> c` for `id("")`.

`Type.instantiate` is used to generate a non-polymorphic type from a polymorphic type, a so-called "instance", for instance `q -> q` is an instance of `forall a. a -> a`. A limitation of HM type systems is that types can be "generalized", i.e. made polymorphic [only in let expressions](https://www.wikiwand.com/en/Hindley%E2%80%93Milner_type_system#Let-polymorphism), otherwise the type system would be undecidable.

The `letLevel` is used as an optimization for the type generalization process, see https://okmij.org/ftp/ML/generalization.html

> 2. resolveType -> Correct

> 3. Type rewriting
This is really just an experiment to design expressive, yet simple to implement types.
It is basically just term rewriting, see https://github.com/nathsou/girafe for instance, I am still not sure wether it's a good idea, as it might be a bit too expressive, It would maybe be a better fit in a language with dependent types. But it's convenient to extract type parameters or to perform simple computations on types, like:

``` 
type ElementType<Array<t>> = t
type IsEmpty<[]> = True
type IsEmpty<_:_> = False
```

> 4. unifyVar
Usually, we would use substitutions (mappings from type names/ids to types) as the result of the unification process but this is quite inefficient and hard to work with in a non functional language so I implemented the optimizations used in https://github.com/tomprimozic/type-systems (see algorithm w) where each type variable contains a mutable reference to the type it is linked with (via unification).

Example:

```rust
let n = 3
```

1. `n` is first assigned a fresh unbound type variable `a`
2. The rhs of the assignment is inferred to be of type `Num`
3. the lhs and rhs types are unified: `unify(a, Num)`

The result of `unify(a, Num)` would normally be a substitution dictionary: `{ a: Num }`
But we would then need to apply the substitution on all subsequent types.
Instead, the `unifyVar` function directly links the unbound type variable of `a` to `Num` (using mutation).

**Comment by Xerios** [comment]
Thanks for the explanation, I already rewrote the parser and lexer as those are pretty simple concepts. 

Aww, It's sad to hear that it's not possible. Right after I managed fix my problem by adding var ids to `show()`, which made it simpler to understand the behavior.

> it's a bit complex and not super efficient

It's fast enough, but it's definitely complex that's for sure. My mind is simply not built for algebra-heavy code 😅 

I do quite like the type system, and I read that "HM by itself can't support such cases", which made me think perhaps there's a simple way to extend it. You're probably right, I will be more productive with a simpler type system, but digging around the type system really did open my eyes to certain techniques I wasn't aware of.

My main issue in the past was that my compiler rewrites lacked proper structure, my code would eventually end up so big that I could literally not fit it inside my head. This drove me insane as it happened 3 times, so after researching various other compilers I thought maybe the issue is that I'm using the wrong language.

I decided to start learning Rescript (had problems with installing Ocaml on windows / wsl), thinking that it would solve my problem. That's when I discovered yolang-res, which led me to Poy, which was more recent yet you still went with TS despite knowing Rescript. Seeing your code structure and how things were connected made me realize why my rewrites failed, so I have to thank you for that 😄 

Leaving the type system aside. I do have few other questions about the structure itself. 
Just want to know if I understood it correctly:
* **Bitter AST**: This is the typed version and final form after type checking phase, akin to Semantic AST.
* **Sweet AST**: This is straight from the parser, as described in yolang "sugared representations". At first I thought this was an immutable representation, which was the core truth of parser. Whereas Bitter is the version that's may get transformed beyond its' original shape.
  * This is what I understood from yolang where Bitter is mostly modified/generated. Later I discovered you do mutate some of Sweet expressions during type checking. So I guess, sweet is "simpler" version, bitter is "hardened"?
* **Js AST**: This feels like a very separated structure as it JS code could've been created through Bitter directly. Perhaps this is to allow target other languages if needed?
  * I'm a bit puzzled to why scoping rules live inside the Js AST when it could've been part of Bitter. Maybe this is due other languages having different rules when it comes to scopes?

**Comment by nathsou** [comment]
> which made me think perhaps there's a simple way to extend it.

There are extensions that can handle subtyping you might want to look into that if you still want a HM type system.

> My main issue in the past was that my compiler rewrites lacked proper structure

I can relate, I have started multiple hobby languages as you've seen and I tend to get overambitious. I have not read a great deal about programming language implementation as for my hobby projects, I like to first try to discover concepts by myself and then do some research about it. So for Poy I have managed my expectations, by not working on it super hard but trying to go back regularly. This is why I wrote a basic roadmap with byte-sized and rewarding tasks. The main hurdles in my previous projects was memory management as I was targeting WASM or LLMV, so by deciding to target JS with Poy, I can focus on other areas.
I also explicitely defined code refactoring tasks in the roadmap to clean up ugly parts from previous tasks and add better error messages. In particular I know that I will need to clean up the way type parameters are handled as it's quite hacky right now in my opnion so I will try to do some research on that topic.

> I decided to start learning Rescript

Rescript is very nice but for Poy I decided to got back to TypeScript mainly because I went through a journey, from OO, to Functional, now back to procedural programming and TypeScript, as a multi-paradigm language fits my current coding style pretty well. (My ideal language is of course closer to Poy/Rust). The long-term goal (if I ever get there) would be to rewrite Poy in Poy once it's stable enough, but this will require some basic tooling and better error messages, this is why I don't really care about performance (both for the compiler and for the generated JS code).
Of course, Rescript might be a good fit for you, depending on what you are looking for.

> Sweet AST: you do mutate some of Sweet expressions during type checking

Ideally, sweet (unsugared, I know this is ironic) expressions would be immutable and the inferencer would produce a new kind of AST with additional information but I was a bit lazy and instead added pieces of information only known during inference to the sweet AST (like isIterator, isNative, extension uuids, etc..).

> Js AST

JS code could be generated directly from Bitter ASTs, however using an abstraction makes it easier to design target-specific optimizations later on and to enforce formatting without duplication and so on.

> I'm a bit puzzled to why scoping rules live inside the Js AST when it could've been part of Bitter. Maybe this is due other languages having different rules when it comes to scopes?

That's right, Bitter still encodes "poy" scopes, where blocks are expressions, which is different from JS.
Once again, this will make bitter ASTs easier to optimize.
Bitter ASTs should not care about the specific target (as I could add other targets like Rescript which have the same scope behavior as Poy).

**Comment by Xerios** [comment]
> sweet (unsugared, I know this is ironic)

I thought it was pretty clever, in a sense Poy is a syntax sugar over more bitter/ugly javascript

Thanks for the explanations 👍 
It'll take me some time before I can push any more of my contributions. I try to keep my PRs as clean as possible and that takes time.
Rewriting my old type system with the new structure is gonna be a big challenge, followed up with migrating multitude of tests and integration process.

**Comment by nathsou** [comment]
Good luck then on the type system rewrite, it will probably be very interesting!

**Pull request closed without merging**
