### PR TITLE
Add precedences file

### PR DESCRIPTION
**Pull request by Xerios**
This is straight inspired from acorn parser which uses precedence climbing.
Current parser has a serious bad case of nested callbacks, making difficult to debug.

The example file is written in Poy, with exception of bitwise XOR test which isn't available in Poy, but that one is commented out.

Due to big difference with my parser, I can't make an easy PR, but here's the main important parts which you can integrate.

```ts

const enum PRECEDENCE {
  logicalOR  = 1,  //  ||
  logicalAND = 2,  //  &&
  bitwiseOR  = 3,  //  |
  bitwiseXOR = 4,  //  ^
  bitwiseAND = 5,  //  &
  equality   = 6,  //  ==/!=/===/!==
  relational = 7,  //  </>/<=/>=
  // bitShif = 8,  //  <</>>/>>>
  plusMin    = 9,  // +/-
  modulo     = 10, //  %
  star       = 10, // *
  slash      = 10, // /
  starstar   = 11, // **
}

// operators
'+':   Token.Symbol('+',   { binop: PRECEDENCE.plusMin }),
'-':   Token.Symbol('-',   { binop: PRECEDENCE.plusMin }),
'*':   Token.Symbol('*',   { binop: PRECEDENCE.star }),
'/':   Token.Symbol('/',   { binop: PRECEDENCE.slash }),
'mod': Token.Symbol('mod', { binop: PRECEDENCE.modulo }),
'**':  Token.Symbol('**',  { binop: PRECEDENCE.starstar, beforeExpr: true }),

'==': Token.Symbol('==',   { binop: PRECEDENCE.equality }),
'!=': Token.Symbol('!=',   { binop: PRECEDENCE.equality }),
'<':  Token.Symbol('<', { binop: PRECEDENCE.relational }),
'<=': Token.Symbol('<=', { binop: PRECEDENCE.relational }),
'>':  Token.Symbol('>', { binop: PRECEDENCE.relational }),
'>=': Token.Symbol('>=', { binop: PRECEDENCE.relational }),

'and': Token.Symbol('and', { binop: PRECEDENCE.logicalAND }),
'or':  Token.Symbol('or', { binop: PRECEDENCE.logicalOR }),

'&': Token.Symbol('&', { binop: PRECEDENCE.bitwiseAND }),
'|': Token.Symbol('|', { binop: PRECEDENCE.bitwiseOR }),
'^': Token.Symbol('^', { binop: PRECEDENCE.bitwiseXOR }),

//------

binExprStart = (): Expr => this.parseExprOp(this.unaryExpr(), -1, false)
parseExprOp = (lhs: Expr, minPrec: number, noIn: boolean): Expr => {
  const symbType = currToken.variant === 'Symbol' ? currToken : null
  const prec = (symbType && 'binop' in symbType) ? symbType?.binop ?? null : null

  if (prec !== null && (!noIn || symbType?.symb !== 'in')) {
    if (prec > minPrec) {
      const tokVal = symbType?.symb
      next()
      const rhs = parseExprOp(unaryExpr(), prec, noIn)
      const exprNode = Expr.Binary({
        lhs, op: tokVal as BinaryOp, rhs,
      })
      return parseExprOp(exprNode, minPrec, noIn)
    }
  }

  return lhs
}

```

### CODE REVIEW

**Comment by nathsou** [comment]
This is interesting but to me recursive descent is much easier to read than precedence climbing, no complex machinery.
Nested callbacks are everywhere in this code base if you look at match calls for instance so this is not particularly an issue for me.

```ts
    function logicalOrExpr(): Expr {
        return binaryExpr(logicalAndExpr, ['or']);
    }

    function logicalAndExpr(): Expr {
        return binaryExpr(equalityExpr, ['and']);
    }

    function equalityExpr(): Expr {
        return binaryExpr(comparisonExpr, ['==', '!=']);
    }

    function comparisonExpr(): Expr {
        return binaryExpr(additionExpr, ['<', '<=', '>', '>=']);
    }

    function additionExpr(): Expr {
        return binaryExpr(multiplicationExpr, ['+', '-']);
    }

    function multiplicationExpr(): Expr {
        return binaryExpr(powExpr, ['*', '/', 'mod']);
    }

    function powExpr(): Expr {
        return binaryExpr(unaryExpr, ['**']);
    }
   ```

**Comment by Xerios** [comment]
Feel free to come back to this once you grow tired of navigating the extremely lengthy stacktraces 😉

**Comment by nathsou** [comment]
I might use precedence climbing in the poy rewrite of the compiler (If I ever get there ^^) as by then match expressions will compile to much flatter/easier to debug JS. Out of curiosity, in what case did you need to navigate the parsing stacktraces?

**Comment by Xerios** [comment]
It was polluting my traversal hooks in my debugging tool. Besides that it was mostly to align it with my old parser.

Code_RYpnXlvNcP

**Pull request closed without merging**
