### PR TITLE
Add build and examples files watcher

### PR DESCRIPTION
**Pull request by Xerios**
Code_hlpQqNA13R

> `npm start` 

Guaranteed to improve your dev experience 😉 

* Runs watch command + using chokidar monitors any `build/**/*.js` and `examples/*.poy` file changes. 
* Also remembers latest changed `.poy` example file
  * if you want to run any example you can just Ctrl+S on any example and it will run on it (even when having no changes).

For some reason esbuild fails to display colors for its errors when run through this script, I'm using swc for my own version which doesn't have this issue.

### CODE REVIEW

**Comment by Xerios** [comment]
Sad to see this PR not merged yet, this is **THE most useful** change I've submitted so far 🙃 

I'm gonna use this post to introduce you to another extremely useful new feature from typescript (eventually to be part of JS):  [explicit resource management](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html).

It works similarly to defer from golang, works as a syntax sugar for now (results in `try {...} finally {dispose}`) and it only requires two Symbols to be defined for it to work.
 
I've been using it to do things such as:
```ts
decl = (): Decl => {
  using _ = this.useAttributes()
  // do stuff
  { 
    // using is scope-dependant
    using {attrs} = this.useAttributes()
    // at end of scope it reverts to previous attributes
  }
}
```
or
```ts
using _ = this.ctx.push('funStmt', { canDeclareTypes: true })
```
or
```ts
function ezzz_group(text: string): Disposable {
  console.group(text)
  return { [Symbol.dispose]: console.groupEnd }
}
using _ = ezzz_group('easy console.group() wrap')
```

**Comment by nathsou** [comment]
Hey!

As much as I appreciate your enthusiasm to open PRs, your vision of the project doesn't necessarily align with mine, for instance I would like to minimize the number of dependencies (even dev deps) used in the project and this PR is introducing two new deps. Your fork and this repo don't have to align on every decision and this is totally fine, this is why forks exist after all. 

Your watcher looks good, however by simply running `bun run src/main.ts examples/Match.poy` for instance, bun handles type removal and interpretation in a single command, I also get the true locations for errors and I can CTRL/CMD + click to open the corresponding line in my editor. I prefer simpler solutions when possible and this workflow works just fine for me for now without adding deps, my focus on this project is not on tooling right now (see the roadmap).

We should also probably discuss the improvements you want to include in an issue instead of expecting me to merge your PRs right away so that you don't spend time working on nice features which might not fit my personal goals for the project.

The same applies for your test block PR, it's very nice but I had something quite different in mind so if you opened a discussion, we could have discussed about the details beforehand.

Maybe I made the repo public a bit too soon, as I'm very much still figuring out basic design decisions and implementation details and I am not ready to stray too far away from the roadmap I planned which is what I should really focus on.

As for the resource management feature, thanks for sharing, I quite religiously follow TypeScript releases so I read about it and your example with attributes is interesting, I might do something similar.

Cheers and happy coding!

**Comment by Xerios** [comment]
Np, don't worry about me throwing stuff at this project. I'm very well aware of the differences in vision and method of working. This was made clear the moment you reacted to my first PR (Unions). 

I'm retrofitting an existing project, which is way more messy than the careful planning and development you've been doing so far.

Although after I started building my version, quite few of your new commits and changes very strikingly similar to mine which made me excited to contribute. As a matter of fact, I was never (and am still not) expecting any of my PRs to be merged at all 😉. Nor do I wish to impede on your design process or development of Poy. My PRs are here to simply share some ideas, anything beyond is just an extra.

---

I was curious about your workflow, seeing you're using `bun` I can't say I'm familiar with it, mostly because they've always had some very poor windows support.

I do stand by my choice of words for this PR though. It doesn't do much besides simply spawning one watcher and execute another command on file change, you still get true locations for errors and everything is as-if you've simply opened two terminals one with watcher and one with `npm run`. 
* The colored errors issue I mentioned is only present on windows afaik due to powershell being a pain in the ass to work with sometimes.
* Sure, consolas was a pointless inclusion just for fancier logs. Truth to be told, I don't use it myself personally and frankly I shouldn't have included it at all.
* Chokidar however is an essential watching library which handles a lot of nasty cross-platform issues. Since you didn't enforce the node version inside your package.json, this was an obvious catch-all choice for this PR.

---

**However**, we all got our own workflows. If you don't see the value in this commit and you're perfectly fine with your current workflow then it's alright, simply decline the PR, no need to elaborate. Poy is a young project, and I'm glad that you've open-sourced it early, because without it I wouldn't have realized that there's a way more elegant way of structuring a compiler in TS. 

So do not worry about declining my PRs, don't pay too much attention to my suggestions if they don't align with your goals. At worst, they're mostly here to show love and appreciation of your work ❤️

**Comment by nathsou** [comment]
Thanks for you understanding :) I do appreciate your suggestions and I'm sure I could learn a lot from your ideas and experience so if you have suggestions/remarks, of course don't hesitate to open a discussion/issue.
Again your support is much appreciated and is motivating me to continue working on the project :)

**Pull request closed without merging**
